import { type Context } from '@deepseek-ai/cordis';
import { TypertRemoteService } from '@deepseek-ai/dsh-typert-protocol';
import type { Agent } from '@deepseek-ai/dsh-agent';
import type { WorkflowRun, WorkflowDefinition } from '../shared/types.js';
import type { AssociateSessionWorkflowRequest, BrowseDirectoriesRequest, BrowseDirectoriesResult, ContextFilePreview, CreateOutputDirectoryRequest, DiscardSessionDraftRequest, DraftRequest, DraftResult, ImportMarkdownRequest, PendingEditProposalSummary, PendingSessionDraftSummary, PreviewContextFileRequest, RemoveWorkflowRequest, RemoveWorkflowResult, RunActionRequest, SaveWorkflowRequest, SessionDraftRequest, SessionPreviewContextFileRequest, SessionRunActionRequest, SessionRunTargetRequest, SessionWorkflowAssociation, SessionWorkflowEditProposal, SessionWorkflowEditProposalActionRequest, SessionWorkflowEditProposalUpdateRequest, SessionEditorStatusRequest, SessionWorkflowSaveRequest, SessionWorkflowSaveResult, SessionWorkflowState, StartRunRequest, WorkflowSummary } from '../shared/types.js';
export declare const name = "dsh-workflow-plugin";
/** Host business service for saved workflow graphs and their Agent-driven runs. */
export default class WorkflowService extends TypertRemoteService {
    static inject: string[];
    private readonly storage;
    private readonly ready;
    private readonly controllers;
    private readonly runPromises;
    private readonly pauseResolvers;
    private readonly actionQueues;
    private readonly runUpdateQueues;
    private readonly plannerControllers;
    private readonly plannerPromises;
    private readonly editorStatuses;
    constructor(ctx: Context);
    list(): Promise<readonly WorkflowSummary[]>;
    listPendingEditProposals(): Promise<readonly PendingEditProposalSummary[]>;
    listPendingSessionDrafts(): Promise<readonly PendingSessionDraftSummary[]>;
    private summaries;
    get(workflowId: string): Promise<WorkflowDefinition>;
    sessionState(sessionId: string): Promise<SessionWorkflowState>;
    sessionEditorStatus(sessionId: string, request: SessionEditorStatusRequest & {
        readonly clientId: string;
    }): Promise<void>;
    sessionEditProposalUpdate(sessionId: string, request: SessionWorkflowEditProposalUpdateRequest): Promise<SessionWorkflowEditProposal>;
    sessionEditProposalApply(sessionId: string, request: SessionWorkflowEditProposalActionRequest): Promise<WorkflowDefinition>;
    sessionEditProposalDiscard(sessionId: string, request: SessionWorkflowEditProposalActionRequest): Promise<void>;
    sessionGet(sessionId: string, workflowId: string): Promise<WorkflowDefinition>;
    sessionAssociate(sessionId: string, request: AssociateSessionWorkflowRequest): Promise<SessionWorkflowAssociation>;
    sessionSave(sessionId: string, request: SessionWorkflowSaveRequest): Promise<SessionWorkflowSaveResult>;
    sessionDiscardDraft(sessionId: string, request: DiscardSessionDraftRequest): Promise<void>;
    sessionRuns(sessionId: string, workflowId: string): Promise<readonly WorkflowRun[]>;
    sessionGetRun(sessionId: string, request: SessionRunTargetRequest): Promise<WorkflowRun>;
    sessionPreviewFile(sessionId: string, request: SessionPreviewContextFileRequest): Promise<ContextFilePreview>;
    sessionGenerateDraft(sessionId: string, request: SessionDraftRequest, signal: AbortSignal): Promise<DraftResult>;
    sessionStartRun(sessionId: string, request: StartRunRequest): Promise<WorkflowRun>;
    sessionAction(sessionId: string, request: SessionRunActionRequest): Promise<WorkflowRun>;
    save(request: SaveWorkflowRequest): Promise<WorkflowDefinition>;
    removeWorkflow(request: RemoveWorkflowRequest): Promise<RemoveWorkflowResult>;
    importMarkdown(request: ImportMarkdownRequest): Promise<WorkflowDefinition>;
    previewFile(request: PreviewContextFileRequest): Promise<ContextFilePreview>;
    browseDirectories(request: BrowseDirectoriesRequest): Promise<BrowseDirectoriesResult>;
    createOutputDirectory(request: CreateOutputDirectoryRequest): Promise<string>;
    generateDraft(request: DraftRequest, signal: AbortSignal, parentAgent?: Agent): Promise<DraftResult>;
    private handlePowernodeCommand;
    private startPowernodePlanner;
    private executePowernodeEdit;
    private executePowernodeGoal;
    private inspectSession;
    private resolveSessionId;
    private requireSessionWorkflow;
    runs(workflowId: string): Promise<readonly WorkflowRun[]>;
    getRun(runId: string): Promise<WorkflowRun>;
    startRun(request: StartRunRequest): Promise<WorkflowRun>;
    private startRunInternal;
    private prepareRun;
    private persistAndStartRun;
    action(request: RunActionRequest): Promise<WorkflowRun>;
    private performAction;
    private enqueueRunAction;
    private captureContexts;
    private taskSignatures;
    private validatedReusableArtifacts;
    private applyRevision;
    private executeRun;
    private runTask;
    private verifyRun;
    private currentModel;
    private waitAtPauseBoundary;
    private setTask;
    private updateRun;
    private recordTaskProgress;
    private finishUnexpected;
    private stopActiveRuns;
}
//# sourceMappingURL=index.d.ts.map