/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { AssociateSessionWorkflowRequest, BrowseDirectoriesRequest, BrowseDirectoriesResult, ContextFilePreview, CreateOutputDirectoryRequest, DiscardSessionDraftRequest, DraftRequest, DraftResult, ImportMarkdownRequest, PendingEditProposalSummary, PendingSessionDraftSummary, PreviewContextFileRequest, RemoveWorkflowRequest, RemoveWorkflowResult, RunActionRequest, SaveWorkflowRequest, SessionDraftRequest, SessionEditorStatusRequest, SessionPreviewContextFileRequest, SessionRunActionRequest, SessionRunTargetRequest, SessionWorkflowAssociation, SessionWorkflowEditProposal, SessionWorkflowEditProposalActionRequest, SessionWorkflowEditProposalUpdateRequest, SessionWorkflowSaveRequest, SessionWorkflowSaveResult, SessionWorkflowState, StartRunRequest, WorkflowDefinition, WorkflowRun, WorkflowSummary } from 'dsh-workflow-plugin/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$647368576f726b666c6f77 {
    action: (request: RunActionRequest) => Promise<RemoteResult<WorkflowRun>>
    browseDirectories: (request: BrowseDirectoriesRequest) => Promise<RemoteResult<BrowseDirectoriesResult>>
    createOutputDirectory: (request: CreateOutputDirectoryRequest) => Promise<RemoteResult<string>>
    generateDraft: (request: DraftRequest, signal?: AbortSignal) => Promise<RemoteResult<DraftResult>>
    get: (workflowId: string) => Promise<RemoteResult<WorkflowDefinition>>
    getRun: (runId: string) => Promise<RemoteResult<WorkflowRun>>
    importMarkdown: (request: ImportMarkdownRequest) => Promise<RemoteResult<WorkflowDefinition>>
    list: () => Promise<RemoteResult<readonly WorkflowSummary[]>>
    listPendingEditProposals: () => Promise<RemoteResult<readonly PendingEditProposalSummary[]>>
    listPendingSessionDrafts: () => Promise<RemoteResult<readonly PendingSessionDraftSummary[]>>
    previewFile: (request: PreviewContextFileRequest) => Promise<RemoteResult<ContextFilePreview>>
    removeWorkflow: (request: RemoveWorkflowRequest) => Promise<RemoteResult<RemoveWorkflowResult>>
    runs: (workflowId: string) => Promise<RemoteResult<readonly WorkflowRun[]>>
    save: (request: SaveWorkflowRequest) => Promise<RemoteResult<WorkflowDefinition>>
    sessionAction: (sessionId: string, request: SessionRunActionRequest) => Promise<RemoteResult<WorkflowRun>>
    sessionAssociate: (sessionId: string, request: AssociateSessionWorkflowRequest) => Promise<RemoteResult<SessionWorkflowAssociation>>
    sessionDiscardDraft: (sessionId: string, request: DiscardSessionDraftRequest) => Promise<RemoteResult<void>>
    sessionEditorStatus: (sessionId: string, request: SessionEditorStatusRequest & { readonly clientId: string; }) => Promise<RemoteResult<void>>
    sessionEditProposalApply: (sessionId: string, request: SessionWorkflowEditProposalActionRequest) => Promise<RemoteResult<WorkflowDefinition>>
    sessionEditProposalDiscard: (sessionId: string, request: SessionWorkflowEditProposalActionRequest) => Promise<RemoteResult<void>>
    sessionEditProposalUpdate: (sessionId: string, request: SessionWorkflowEditProposalUpdateRequest) => Promise<RemoteResult<SessionWorkflowEditProposal>>
    sessionGenerateDraft: (sessionId: string, request: SessionDraftRequest, signal?: AbortSignal) => Promise<RemoteResult<DraftResult>>
    sessionGet: (sessionId: string, workflowId: string) => Promise<RemoteResult<WorkflowDefinition>>
    sessionGetRun: (sessionId: string, request: SessionRunTargetRequest) => Promise<RemoteResult<WorkflowRun>>
    sessionPreviewFile: (sessionId: string, request: SessionPreviewContextFileRequest) => Promise<RemoteResult<ContextFilePreview>>
    sessionRuns: (sessionId: string, workflowId: string) => Promise<RemoteResult<readonly WorkflowRun[]>>
    sessionSave: (sessionId: string, request: SessionWorkflowSaveRequest) => Promise<RemoteResult<SessionWorkflowSaveResult>>
    sessionStartRun: (sessionId: string, request: StartRunRequest) => Promise<RemoteResult<WorkflowRun>>
    sessionState: (sessionId: string) => Promise<RemoteResult<SessionWorkflowState>>
    startRun: (request: StartRunRequest) => Promise<RemoteResult<WorkflowRun>>
  }
  interface TypertRemoteMap {
    'dshWorkflow/action': (request: RunActionRequest) => Promise<RemoteResult<WorkflowRun>>
    'dshWorkflow/browseDirectories': (request: BrowseDirectoriesRequest) => Promise<RemoteResult<BrowseDirectoriesResult>>
    'dshWorkflow/createOutputDirectory': (request: CreateOutputDirectoryRequest) => Promise<RemoteResult<string>>
    'dshWorkflow/generateDraft': (request: DraftRequest, signal?: AbortSignal) => Promise<RemoteResult<DraftResult>>
    'dshWorkflow/get': (workflowId: string) => Promise<RemoteResult<WorkflowDefinition>>
    'dshWorkflow/getRun': (runId: string) => Promise<RemoteResult<WorkflowRun>>
    'dshWorkflow/importMarkdown': (request: ImportMarkdownRequest) => Promise<RemoteResult<WorkflowDefinition>>
    'dshWorkflow/list': () => Promise<RemoteResult<readonly WorkflowSummary[]>>
    'dshWorkflow/listPendingEditProposals': () => Promise<RemoteResult<readonly PendingEditProposalSummary[]>>
    'dshWorkflow/listPendingSessionDrafts': () => Promise<RemoteResult<readonly PendingSessionDraftSummary[]>>
    'dshWorkflow/previewFile': (request: PreviewContextFileRequest) => Promise<RemoteResult<ContextFilePreview>>
    'dshWorkflow/removeWorkflow': (request: RemoveWorkflowRequest) => Promise<RemoteResult<RemoveWorkflowResult>>
    'dshWorkflow/runs': (workflowId: string) => Promise<RemoteResult<readonly WorkflowRun[]>>
    'dshWorkflow/save': (request: SaveWorkflowRequest) => Promise<RemoteResult<WorkflowDefinition>>
    'dshWorkflow/sessionAction': (sessionId: string, request: SessionRunActionRequest) => Promise<RemoteResult<WorkflowRun>>
    'dshWorkflow/sessionAssociate': (sessionId: string, request: AssociateSessionWorkflowRequest) => Promise<RemoteResult<SessionWorkflowAssociation>>
    'dshWorkflow/sessionDiscardDraft': (sessionId: string, request: DiscardSessionDraftRequest) => Promise<RemoteResult<void>>
    'dshWorkflow/sessionEditorStatus': (sessionId: string, request: SessionEditorStatusRequest & { readonly clientId: string; }) => Promise<RemoteResult<void>>
    'dshWorkflow/sessionEditProposalApply': (sessionId: string, request: SessionWorkflowEditProposalActionRequest) => Promise<RemoteResult<WorkflowDefinition>>
    'dshWorkflow/sessionEditProposalDiscard': (sessionId: string, request: SessionWorkflowEditProposalActionRequest) => Promise<RemoteResult<void>>
    'dshWorkflow/sessionEditProposalUpdate': (sessionId: string, request: SessionWorkflowEditProposalUpdateRequest) => Promise<RemoteResult<SessionWorkflowEditProposal>>
    'dshWorkflow/sessionGenerateDraft': (sessionId: string, request: SessionDraftRequest, signal?: AbortSignal) => Promise<RemoteResult<DraftResult>>
    'dshWorkflow/sessionGet': (sessionId: string, workflowId: string) => Promise<RemoteResult<WorkflowDefinition>>
    'dshWorkflow/sessionGetRun': (sessionId: string, request: SessionRunTargetRequest) => Promise<RemoteResult<WorkflowRun>>
    'dshWorkflow/sessionPreviewFile': (sessionId: string, request: SessionPreviewContextFileRequest) => Promise<RemoteResult<ContextFilePreview>>
    'dshWorkflow/sessionRuns': (sessionId: string, workflowId: string) => Promise<RemoteResult<readonly WorkflowRun[]>>
    'dshWorkflow/sessionSave': (sessionId: string, request: SessionWorkflowSaveRequest) => Promise<RemoteResult<SessionWorkflowSaveResult>>
    'dshWorkflow/sessionStartRun': (sessionId: string, request: StartRunRequest) => Promise<RemoteResult<WorkflowRun>>
    'dshWorkflow/sessionState': (sessionId: string) => Promise<RemoteResult<SessionWorkflowState>>
    'dshWorkflow/startRun': (request: StartRunRequest) => Promise<RemoteResult<WorkflowRun>>
  }
  interface TypertRemoteNamespaceMap {
    'dshWorkflow': TypertRemoteNamespace$647368576f726b666c6f77
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
